set nocompatible
let $LANG = 'en'  "set message language
set langmenu=en   "set menu's language of gvim. no spaces beside '='

" 缩进制表符相关
set expandtab
set tabstop=4
set softtabstop=4
set autoindent

set mouse=a
set encoding=utf-8
let &t_ut=''
set list
set listchars=tab:>-
set scrolloff=5
set tw=0
set foldmethod=indent
set foldlevel=99
set laststatus=2
set autochdir
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

let mapleader=' '
syntax on
set relativenumber
set wildmenu
set wrap
set showcmd

set hlsearch
set incsearch
set ignorecase
set smartcase

noremap <LEADER><CR> :nohlsearch<CR>

noremap J 6j
noremap K 6k
noremap n nzz
noremap N Nzz

" INSERT MODE: 自动匹配括号
inoremap ( ()<LEFT>
inoremap { {}<LEFT>
inoremap [ []<LEFT>

" INSERT MODE: 快速移动光标
inoremap <C-a> <C-o>^ " 行首
inoremap <C-e> <C-o>$ " 行尾
inoremap <C-u> <SPACE><C-o>d^ " 删除光标前

" 多窗口 
map <C-\> :set splitright<CR>:vsplit<CR>
noremap s <nop>
map sl :set nosplitright<CR>:vsplit<CR>
map sh :set splitright<CR>:vsplit<CR>
map sj :set splitbelow<CR>:split<CR>
map sk :set nosplitbelow<CR>:split<CR>
map <LEADER>j <C-w>j
map <LEADER>k <C-w>k
map <LEADER>h <C-w>h
map <LEADER>l <C-w>l

" 窗口大小设置
map <LEADER><up> :res +5<CR>
map <LEADER><down> :res -5<CR>
map <LEADER><left> :vertical resize +5<CR>
map <LEADER><right> :vertical resize -5<CR>

" 标签页
nnoremap <C-o> :tabe<CR>:e 
nmap tt :tabe<CR>
nmap th :-tabnext<CR>
nmap tl :+tabnext<CR>

" 占位符<++>：'<,'>normal ...
map <LEADER><LEADER> <Esc>:/<++><CR>:nohlsearch<CR>c4l

" 光标后退/前进
nnoremap - <C-o>
nnoremap = <C-i>


